name: Scala Steward
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: scala-steward-org/scala-steward-action@v2
        with:
          cache-ttl: "0s"
